@startuml

object "<u>ships[0]:Ship</u>" as titanic{
  shipName = "Titanic"
  yearBuilt = "March31st,1909"
}

object "<u>ships[1]:CruiseShip</u>" as gemini{
  shipName = "MVGemini"
  yearBuilt = "May30th,1991"
  maxNumberPassengers = 100
}

object "<u>ships[2]:CargoShip</u>" as given{
  shipName = "EverGiven"
  yearBuilt = "September25th,2018"
  cargoCapacityInTonnage = 220940
}

titanic <|-- gemini
titanic <|-- given

@enduml
